apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-telemetry-webui
  labels:
    app: f1-telemetry
spec:
  replicas: 1
  template:
    metadata:
      name: f1-telemetry-webui
      labels:
        app: f1-telemetry-webui
    spec:
      containers:
        - name: f1-telemetry-webui
          image: quay.io/ppatierno/f1-telemetry-webui:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap:9092
      restartPolicy: Always
  selector:
    matchLabels:
      app: f1-telemetry-webui
---
apiVersion: v1
kind: Service
metadata:
  name: f1-telemetry-webui
  labels:
    app: f1-telemetry
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: f1-telemetry-webui
  type: ClusterIP